### ISSUE TITLE
[FEATURE] List of clients in alphabetical order (if you want them)

### ISSUE THREAD

**Issue by mostwise** [Minecraft-Anarchy/minecraft-hack-clients#7]
Ananta
AquaticClient
Ares
BaseClient
Bedtrap
bhack
BigRat
BleachHack
Cake-client
CookieClient
Cosmos
CXClient
Delta
DevilClient
Equinox
Ferox
FrogHack
FrostBurn
Future
gamesense-plus-2
Hache
Haze
Impact
Inertias
Infinity
JexClients
KAMI
KAMIBlue
Konas
Lambda
LiquidBounces
MatHax
Mercury
MeteorClient
Onigiri
PepsiMod
Phobos
Postman
Pyro
Resilience
RusherHack
Salhack
Seppuku
Spidersense
Steak-Hax
Tensor
TrollHack
Wurst
Wurst+2
Wurst+3
Xeno
Yasashii-Client

**Comment by Maniacsss** [comment]
Thanks but we need the version and where to get it (github link or website).

**Comment by mostwise** [comment]
@Maniacxxx Alright, I have been working on a new list based on your guys' list. This will take a while as copying over md isn't as easy. I will make a pull req with just the table and nothing else. Thanks!

**Comment by Maniacsss** [comment]
@shxrkyylol alright looking forward to it.

**Comment by Maniacsss** [comment]
@shxrkyylol I just noticed you meant in order lol

**Comment by Maniacsss** [comment]
Alright I ordered them alphabetically.
