### ISSUE TITLE
Contains Xeno.

### ISSUE THREAD

**Issue by surge541** [Minecraft-Anarchy/minecraft-hack-clients#8]
Remove it, I deleted everything I could that was related to Xeno, including the Github and Discord.

Also, it was a fucking awful paste, and I fully regret making it.

Instead I suggest adding Paragon (https://github.com/Wolfsurge/Paragon).

**Comment by Maniacsss** [comment]
Alright I'll make sure I do. Thank you for suggesting another client.

**Comment by surge541** [comment]
No problem 👍

**Comment by Maniacsss** [comment]
Alright did it 👍
